// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAZSeWlQJZbEgZZX1hwlKnFoo8nQF57s',
    appId: '1:399517492333:web:b20e4ed0a8fb6e46394b64',
    messagingSenderId: '399517492333',
    projectId: 'basicapp-bfa89',
    authDomain: 'basicapp-bfa89.firebaseapp.com',
    storageBucket: 'basicapp-bfa89.appspot.com',
    measurementId: 'G-41K8SMTYLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBklvKU1VgXMIOAN7PFmJN3-NtWF-moyxg',
    appId: '1:399517492333:android:e1ef0edf50d7cf7c394b64',
    messagingSenderId: '399517492333',
    projectId: 'basicapp-bfa89',
    storageBucket: 'basicapp-bfa89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN2ZSOWEuBt_rABFu-ht2KSDCu-DIKOR4',
    appId: '1:399517492333:ios:f1883d9ef1f20ec6394b64',
    messagingSenderId: '399517492333',
    projectId: 'basicapp-bfa89',
    storageBucket: 'basicapp-bfa89.appspot.com',
    iosBundleId: 'com.example.basicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgAZSeWlQJZbEgZZX1hwlKnFoo8nQF57s',
    appId: '1:399517492333:web:8162272b25609f6e394b64',
    messagingSenderId: '399517492333',
    projectId: 'basicapp-bfa89',
    authDomain: 'basicapp-bfa89.firebaseapp.com',
    storageBucket: 'basicapp-bfa89.appspot.com',
    measurementId: 'G-QTRY30HJP5',
  );
}